import { readdir, stat } from "node:fs/promises";
import path from "node:path";
import { spawnSync } from "node:child_process";
import readline from "node:readline/promises";

async function markdownFiles(root, prefix="") { const entries = await readdir(root,{withFileTypes:true}); const files=[]; for(const entry of entries.sort((a,b)=>a.name.localeCompare(b.name))){const relative=path.join(prefix,entry.name); if(entry.isDirectory()) files.push(...await markdownFiles(path.join(root,entry.name),relative)); else if(entry.isFile()&&entry.name.endsWith(".md")) files.push(relative);} return files; }
function openEditor(file) { const configured=process.env.VISUAL||process.env.EDITOR; const command=configured || (process.platform==="darwin"?"open":process.platform==="win32"?"notepad":"xdg-open"); const args=configured?[file]:process.platform==="darwin"?["-t",file]:[file]; const result=spawnSync(command,args,{stdio:"inherit"}); if(result.error) throw new Error(`Could not open an editor. Set the EDITOR environment variable, then retry. (${result.error.message})`); }
export async function configureStandards(target,{file:requested,terminal:providedTerminal}={}) { const root=path.join(target,".ai"); if(!(await stat(root).catch(()=>null))?.isDirectory()) throw new Error(`No .ai handbook found in ${target}. Run devcanon init first.`); const files=await markdownFiles(root); let selected=requested; if(!selected){ if(!process.stdin.isTTY) throw new Error("Interactive configuration needs a terminal. Use devcanon configure --file design.md."); const terminal=providedTerminal||readline.createInterface({input:process.stdin,output:process.stdout}); try { console.log("\nChoose a standard to edit:\n"); files.forEach((file,index)=>console.log(`${String(index+1).padStart(2," ")}. ${file}`)); const answer=await terminal.question("\nFile number (or 0 to cancel): "); if(answer==="0") return; const index=Number(answer)-1; if(!Number.isInteger(index)||!files[index]) throw new Error("Invalid selection. Choose one of the displayed file numbers."); selected=files[index]; } finally { if(!providedTerminal) terminal.close(); } }
  const normalized=path.normalize(selected).replace(/^\.ai[\\/]/,""); if(!files.includes(normalized)) throw new Error(`Standard not found: ${selected}. Use devcanon configure to list available files.`); const absolute=path.join(root,normalized); openEditor(absolute); return normalized;
}
