import { writeFile } from "node:fs/promises";
import path from "node:path";

const defaults = { projectType: "web", strictness: "balanced", design: "product", density: "comfortable", accent: "cyan", testing: "standard", security: "high", docs: "three-column" };
const allowed = { projectType: ["web","api","mobile","library","fullstack"], strictness: ["balanced","strict"], design: ["product","editorial","marketing","minimal"], density: ["comfortable","compact"], accent: ["cyan","blue","violet","emerald","amber","rose"], testing: ["standard","high"], security: ["standard","high"], docs: ["three-column","article","api-reference"] };

export function normalizePreset(value = {}) { const preset = { ...defaults, ...value }; for (const [key, values] of Object.entries(allowed)) if (!values.includes(preset[key])) throw new Error(`Invalid preset value for ${key}: ${preset[key]}. Choose: ${values.join(", ")}`); return preset; }
export function encodePreset(value) { return `dc1_${Buffer.from(JSON.stringify(normalizePreset(value))).toString("base64url")}`; }
export function decodePreset(code) { if (!code?.startsWith("dc1_")) throw new Error("Invalid preset code. Expected a code beginning with dc1_."); try { return normalizePreset(JSON.parse(Buffer.from(code.slice(4), "base64url").toString("utf8"))); } catch (error) { if (error.message.startsWith("Invalid preset")) throw error; throw new Error("The preset code is malformed or incomplete."); } }
export async function applyPreset(target, code) { const preset = decodePreset(code); const lines = Object.entries(preset).map(([key,value]) => `- **${key}**: ${value}`).join("\n"); const content = `# Project Preset\n\n## Purpose\nDefine the project-specific choices generated by devcanon preset code \`${code}\`. This file is more specific than general handbook preferences.\n\n## Philosophy\nCustomization may narrow preferences but never weaken security, accessibility, privacy, or data-integrity requirements.\n\n## Best Practices\n${lines}\n\n## Rules\n- Apply these choices consistently in new work.\n- Preserve stronger existing repository conventions.\n- Change this profile through reviewed configuration updates.\n\n## Examples\nA \`${preset.design}\` interface uses the existing token system with \`${preset.density}\` spacing and \`${preset.accent}\` emphasis.\n\n## Anti-patterns\nTreating a preset as permission to redesign existing products or bypass mandatory standards.\n\n## Checklist\n- [ ] The preset matches the product and repository.\n- [ ] Existing conventions and mandatory safeguards remain intact.\n- [ ] Changes to this profile are reviewed with affected code.\n`;
  await writeFile(path.join(target, ".ai", "preset.md"), content);
  await writeFile(path.join(target, ".ai", "preset.json"), `${JSON.stringify({ version: 1, code, preset }, null, 2)}\n`);
  return preset;
}
export { defaults, allowed };
