import { createServer } from "node:http";
import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { randomBytes } from "node:crypto";
import { spawn } from "node:child_process";

async function files(root,prefix=""){const entries=await readdir(root,{withFileTypes:true});const result=[];for(const entry of entries){const relative=path.join(prefix,entry.name);if(entry.isDirectory())result.push(...await files(path.join(root,entry.name),relative));else if(entry.name.endsWith(".md"))result.push(relative);}return result.sort();}
function safe(root,relative){const resolved=path.resolve(root,relative);if(!resolved.startsWith(`${path.resolve(root)}${path.sep}`)||!relative.endsWith(".md"))throw new Error("Invalid standard path.");return resolved;}
function open(url){const command=process.platform==="darwin"?"open":process.platform==="win32"?"cmd":"xdg-open";const args=process.platform==="win32"?["/c","start","",url]:[url];spawn(command,args,{detached:true,stdio:"ignore"}).unref();}
export async function startStudio(target,{onUpdate}={}){const root=path.join(target,".ai");await readdir(root).catch(()=>{throw new Error(`No .ai handbook found in ${target}. Run devcanon init first.`)});const token=randomBytes(24).toString("hex");const html=await readFile(new URL("../studio/index.html",import.meta.url),"utf8");const server=createServer(async(req,res)=>{try{const url=new URL(req.url,"http://127.0.0.1");if(url.pathname==="/"){res.setHeader("Content-Type","text/html; charset=utf-8");return res.end(html.replaceAll("__TOKEN__",token));}if(req.headers.authorization!==`Bearer ${token}`){res.writeHead(403);return res.end("Forbidden");}if(url.pathname==="/api/files")return res.end(JSON.stringify(await files(root)));if(url.pathname==="/api/file"&&req.method==="GET")return res.end(await readFile(safe(root,url.searchParams.get("path")||""),"utf8"));if(url.pathname==="/api/file"&&req.method==="PUT"){const chunks=[];for await(const chunk of req)chunks.push(chunk);await writeFile(safe(root,url.searchParams.get("path")||""),Buffer.concat(chunks));return res.end(JSON.stringify({ok:true}));}if(url.pathname==="/api/update"&&req.method==="POST"){await onUpdate?.();return res.end(JSON.stringify({ok:true}));}res.writeHead(404);res.end("Not found");}catch(error){res.writeHead(400);res.end(error.message);}});await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));const {port}=server.address();const url=`http://127.0.0.1:${port}`;open(url);console.log(`Devcanon Studio opened for ${target}\n${url}\nPress Ctrl+C to close.`);return new Promise(resolve=>{const close=()=>server.close(resolve);process.once("SIGINT",close);process.once("SIGTERM",close);});}
